#cloud-config
# =============================================================================
# Supabase Self-Hosting Cloud-init Konfiguration
# =============================================================================

package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose-plugin
  - git
  - curl
  - jq
  - unzip
  - unattended-upgrades
  - fail2ban
  - ufw

# =============================================================================
# Konfigurationsdateien
# =============================================================================

write_files:
  # -------------------------------------------------------------------------
  # Automatische Sicherheitsupdates
  # -------------------------------------------------------------------------
  - path: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";

  # -------------------------------------------------------------------------
  # Fail2ban Konfiguration
  # -------------------------------------------------------------------------
  - path: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      bantime = 3600
      findtime = 600
      maxretry = 3

  # -------------------------------------------------------------------------
  # Supabase .env Datei
  # -------------------------------------------------------------------------
  - path: /opt/supabase/.env
    permissions: '0600'
    content: |
      # =============================================================================
      # Supabase Self-Hosting Environment Variables
      # Generated by Terraform - Do not edit manually
      # =============================================================================

      # PostgreSQL
      POSTGRES_PASSWORD=${postgres_password}
      POSTGRES_HOST=db
      POSTGRES_PORT=5432
      POSTGRES_DB=postgres

      # JWT
      JWT_SECRET=${jwt_secret}
      JWT_EXPIRY=3600

      # API Keys
      ANON_KEY=${anon_key}
      SERVICE_ROLE_KEY=${service_role_key}

      # URLs
      SITE_URL=https://${acme_domain}
      API_EXTERNAL_URL=https://${acme_domain}
      SUPABASE_PUBLIC_URL=https://${acme_domain}

      # Dashboard
      DASHBOARD_USERNAME=${dashboard_username}
      DASHBOARD_PASSWORD=${dashboard_password}

      # Kong / SSL
      KONG_HTTP_PORT=80
      KONG_HTTPS_PORT=443
      ACME_EMAIL=${acme_email}
      ACME_DOMAIN=${acme_domain}

      # Secrets
      SECRET_KEY_BASE=${secret_key_base}
      VAULT_ENC_KEY=${vault_enc_key}

      # Logflare
      LOGFLARE_API_KEY=${logflare_api_key}

      # S3 Storage
      STORAGE_BACKEND=s3
      S3_ENDPOINT=${s3_endpoint}
      S3_REGION=${s3_region}
      S3_ACCESS_KEY=${s3_access_key}
      S3_SECRET_KEY=${s3_secret_key}
      S3_STORAGE_BUCKET=${s3_storage_bucket}
      S3_BACKUP_BUCKET=${s3_backup_bucket}

      # Backup Notifications
      NOTIFICATION_URLS=${notification_urls}

      # Studio
      STUDIO_DEFAULT_ORGANIZATION=Default Organization
      STUDIO_DEFAULT_PROJECT=Default Project

      # Features
      ENABLE_EMAIL_SIGNUP=true
      ENABLE_EMAIL_AUTOCONFIRM=true
      ENABLE_PHONE_SIGNUP=false
      ENABLE_PHONE_AUTOCONFIRM=false
      ENABLE_ANONYMOUS_USERS=false
      DISABLE_SIGNUP=false

      # SMTP (optional - configure if needed)
      SMTP_ADMIN_EMAIL=
      SMTP_HOST=
      SMTP_PORT=587
      SMTP_USER=
      SMTP_PASS=
      SMTP_SENDER_NAME=Supabase

      # Mailer URLs
      MAILER_URLPATHS_INVITE=/auth/v1/verify
      MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
      MAILER_URLPATHS_RECOVERY=/auth/v1/verify
      MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify

      # PostgREST
      PGRST_DB_SCHEMAS=public,storage,graphql_public

      # Functions
      FUNCTIONS_VERIFY_JWT=false

      # ImgProxy
      IMGPROXY_ENABLE_WEBP_DETECTION=true

      # Pooler
      POOLER_TENANT_ID=supabase

      # Docker Socket (for Vector)
      DOCKER_SOCKET_LOCATION=/var/run/docker.sock

  # -------------------------------------------------------------------------
  # Kong Konfiguration mit ACME/Let's Encrypt
  # -------------------------------------------------------------------------
  - path: /opt/supabase/volumes/api/kong.yml
    content: |
      _format_version: '2.1'
      _transform: true

      ###
      ### Consumers / Users
      ###
      consumers:
        - username: DASHBOARD
        - username: anon
          keyauth_credentials:
            - key: $SUPABASE_ANON_KEY
        - username: service_role
          keyauth_credentials:
            - key: $SUPABASE_SERVICE_KEY

      ###
      ### Access Control List
      ###
      acls:
        - consumer: anon
          group: anon
        - consumer: service_role
          group: admin

      ###
      ### Dashboard credentials
      ###
      basicauth_credentials:
        - consumer: DASHBOARD
          username: $DASHBOARD_USERNAME
          password: $DASHBOARD_PASSWORD

      ###
      ### ACME Plugin for Let's Encrypt
      ###
      plugins:
        - name: acme
          config:
            account_email: $ACME_EMAIL
            api_uri: https://acme-v02.api.letsencrypt.org/directory
            tos_accepted: true
            domains:
              - $ACME_DOMAIN
            storage: redis
            storage_config:
              redis:
                host: kongredis
                port: 6379

      ###
      ### API Routes
      ###
      services:
        ## Open Auth routes
        - name: auth-v1-open
          url: http://auth:9999/verify
          routes:
            - name: auth-v1-open
              strip_path: true
              paths:
                - /auth/v1/verify
          plugins:
            - name: cors
        - name: auth-v1-open-callback
          url: http://auth:9999/callback
          routes:
            - name: auth-v1-open-callback
              strip_path: true
              paths:
                - /auth/v1/callback
          plugins:
            - name: cors
        - name: auth-v1-open-authorize
          url: http://auth:9999/authorize
          routes:
            - name: auth-v1-open-authorize
              strip_path: true
              paths:
                - /auth/v1/authorize
          plugins:
            - name: cors

        ## Secure Auth routes
        - name: auth-v1
          _comment: 'GoTrue: /auth/v1/* -> http://auth:9999/*'
          url: http://auth:9999/
          routes:
            - name: auth-v1-all
              strip_path: true
              paths:
                - /auth/v1/
          plugins:
            - name: cors
            - name: key-auth
              config:
                hide_credentials: false
            - name: acl
              config:
                hide_groups_header: true
                allow:
                  - admin
                  - anon

        ## Secure REST routes
        - name: rest-v1
          _comment: 'PostgREST: /rest/v1/* -> http://rest:3000/*'
          url: http://rest:3000/
          routes:
            - name: rest-v1-all
              strip_path: true
              paths:
                - /rest/v1/
          plugins:
            - name: cors
            - name: key-auth
              config:
                hide_credentials: true
            - name: acl
              config:
                hide_groups_header: true
                allow:
                  - admin
                  - anon

        ## Secure GraphQL routes
        - name: graphql-v1
          _comment: 'PostgREST: /graphql/v1/* -> http://rest:3000/rpc/graphql'
          url: http://rest:3000/rpc/graphql
          routes:
            - name: graphql-v1-all
              strip_path: true
              paths:
                - /graphql/v1
          plugins:
            - name: cors
            - name: key-auth
              config:
                hide_credentials: true
            - name: request-transformer
              config:
                add:
                  headers:
                    - Content-Profile:graphql_public
            - name: acl
              config:
                hide_groups_header: true
                allow:
                  - admin
                  - anon

        ## Secure Realtime routes
        - name: realtime-v1-ws
          _comment: 'Realtime: /realtime/v1/* -> ws://realtime:4000/socket/*'
          url: http://realtime-dev.supabase-realtime:4000/socket
          protocol: ws
          routes:
            - name: realtime-v1-ws
              strip_path: true
              paths:
                - /realtime/v1/
          plugins:
            - name: cors
            - name: key-auth
              config:
                hide_credentials: false
            - name: acl
              config:
                hide_groups_header: true
                allow:
                  - admin
                  - anon
        - name: realtime-v1-rest
          _comment: 'Realtime: /realtime/v1/api/* -> http://realtime:4000/api/*'
          url: http://realtime-dev.supabase-realtime:4000/api
          protocol: http
          routes:
            - name: realtime-v1-rest
              strip_path: true
              paths:
                - /realtime/v1/api
          plugins:
            - name: cors
            - name: key-auth
              config:
                hide_credentials: false
            - name: acl
              config:
                hide_groups_header: true
                allow:
                  - admin
                  - anon

        ## Storage routes
        - name: storage-v1
          _comment: 'Storage: /storage/v1/* -> http://storage:5000/*'
          url: http://storage:5000/
          routes:
            - name: storage-v1-all
              strip_path: true
              paths:
                - /storage/v1/
          plugins:
            - name: cors

        ## Edge Functions routes
        - name: functions-v1
          _comment: 'Edge Functions: /functions/v1/* -> http://functions:9000/*'
          url: http://functions:9000/
          routes:
            - name: functions-v1-all
              strip_path: true
              paths:
                - /functions/v1/
          plugins:
            - name: cors

        ## Analytics routes
        - name: analytics-v1
          _comment: 'Analytics: /analytics/v1/* -> http://analytics:4000/*'
          url: http://analytics:4000/
          routes:
            - name: analytics-v1-all
              strip_path: true
              paths:
                - /analytics/v1/

        ## Secure Database routes
        - name: meta
          _comment: 'pg-meta: /pg/* -> http://meta:8080/*'
          url: http://meta:8080/
          routes:
            - name: meta-all
              strip_path: true
              paths:
                - /pg/
          plugins:
            - name: key-auth
              config:
                hide_credentials: false
            - name: acl
              config:
                hide_groups_header: true
                allow:
                  - admin

        ## Protected Dashboard - catch all remaining routes
        - name: dashboard
          _comment: 'Studio: /* -> http://studio:3000/*'
          url: http://studio:3000/
          routes:
            - name: dashboard-all
              strip_path: true
              paths:
                - /
          plugins:
            - name: cors
            - name: basic-auth
              config:
                hide_credentials: true

  # -------------------------------------------------------------------------
  # Restore Script
  # -------------------------------------------------------------------------
  - path: /opt/supabase/scripts/restore.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -euo pipefail

      # Load environment
      source /opt/supabase/.env

      BACKUP_DATE="$${1:-}"

      if [ -z "$BACKUP_DATE" ]; then
          echo "Usage: $0 YYYY-MM-DD"
          echo ""
          echo "Available backups:"
          aws --endpoint-url "$S3_ENDPOINT" s3 ls "s3://$S3_BACKUP_BUCKET/supabase/" 2>/dev/null | grep backup- | tail -10 || echo "No backups found"
          exit 1
      fi

      echo "=== Supabase Disaster Recovery ==="
      echo "Restoring from backup: $BACKUP_DATE"
      echo ""

      cd /opt/supabase

      # 1. Stop services
      docker compose down || true

      # 2. Download backup from S3
      echo "Downloading backup..."
      BACKUP_FILE=$(aws --endpoint-url "$S3_ENDPOINT" s3 ls "s3://$S3_BACKUP_BUCKET/supabase/" | grep "backup-$BACKUP_DATE" | tail -1 | awk '{print $4}')

      if [ -z "$BACKUP_FILE" ]; then
          echo "ERROR: No backup found for $BACKUP_DATE!"
          exit 1
      fi

      aws --endpoint-url "$S3_ENDPOINT" s3 cp "s3://$S3_BACKUP_BUCKET/supabase/$BACKUP_FILE" /tmp/backup.tar.gz

      # 3. Extract backup
      echo "Extracting backup..."
      mkdir -p /tmp/restore
      tar -xzf /tmp/backup.tar.gz -C /tmp/restore

      # 4. Start database and restore dump
      echo "Restoring database..."
      docker compose up -d db
      sleep 20  # Wait for DB to be ready

      if [ -f /tmp/restore/backup/db-data/backup_dump.sql ]; then
          docker exec -i supabase-db psql -U postgres < /tmp/restore/backup/db-data/backup_dump.sql
          echo "Database restored successfully"
      else
          echo "WARNING: No SQL dump found, only volume data restored"
      fi

      # 5. Start all services
      echo "Starting all services..."
      docker compose up -d

      # 6. Cleanup
      rm -rf /tmp/backup.tar.gz /tmp/restore

      echo ""
      echo "=== Restore completed ==="
      echo "Check status with: docker compose ps"

# =============================================================================
# Ausführungsbefehle
# =============================================================================

runcmd:
  # -------------------------------------------------------------------------
  # System Setup
  # -------------------------------------------------------------------------
  - echo "Starting Supabase setup..."

  # Docker aktivieren
  - systemctl enable docker
  - systemctl start docker

  # Docker Gruppe für ubuntu User
  - usermod -aG docker ubuntu

  # -------------------------------------------------------------------------
  # Supabase Installation
  # -------------------------------------------------------------------------
  - mkdir -p /opt/supabase/volumes/redis
  - mkdir -p /opt/supabase/scripts

  # Supabase Docker Setup klonen
  - git clone --depth 1 https://github.com/supabase/supabase /tmp/supabase-repo

  # Docker Compose Dateien kopieren
  - cp -r /tmp/supabase-repo/docker/* /opt/supabase/

  # Unsere angepasste Kong Konfiguration ist bereits via write_files vorhanden

  # -------------------------------------------------------------------------
  # AWS CLI für S3 Backups installieren
  # -------------------------------------------------------------------------
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
  - unzip -q /tmp/awscliv2.zip -d /tmp/
  - /tmp/aws/install
  - rm -rf /tmp/aws /tmp/awscliv2.zip

  # -------------------------------------------------------------------------
  # Docker Compose anpassen (zusätzliche Services)
  # -------------------------------------------------------------------------
  # Redis für Kong ACME hinzufügen
  - |
    cat >> /opt/supabase/docker-compose.yml << 'ADDITIONALSERVICES'

      # Redis für Kong ACME Zertifikate
      kongredis:
        container_name: supabase-redis
        image: valkey/valkey:7.2
        restart: unless-stopped
        volumes:
          - redis_data:/data
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 5s
          timeout: 5s
          retries: 3

      # Portainer
      portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        ports:
          - "9443:9443"
        labels:
          - "docker-volume-backup.stop-during-backup=false"

      # Uptime Kuma
      uptime-kuma:
        image: louislam/uptime-kuma:latest
        container_name: uptime-kuma
        restart: unless-stopped
        volumes:
          - uptime_kuma_data:/app/data
        ports:
          - "3001:3001"
        labels:
          - "docker-volume-backup.stop-during-backup=false"

      # docker-volume-backup
      backup:
        image: offen/docker-volume-backup:v2
        container_name: backup
        restart: unless-stopped
        environment:
          BACKUP_CRON_EXPRESSION: "0 3 * * *"
          BACKUP_RETENTION_DAYS: "14"
          BACKUP_COMPRESSION: "gz"
          BACKUP_FILENAME: "backup-%Y-%m-%dT%H-%M-%S.{{ .Extension }}"
          AWS_S3_BUCKET_NAME: "${S3_BACKUP_BUCKET}"
          AWS_S3_PATH: "supabase"
          AWS_ENDPOINT: "${S3_ENDPOINT}"
          AWS_ACCESS_KEY_ID: "${S3_ACCESS_KEY}"
          AWS_SECRET_ACCESS_KEY: "${S3_SECRET_KEY}"
          NOTIFICATION_URLS: "${NOTIFICATION_URLS:-}"
          NOTIFICATION_LEVEL: "error"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - supabase_db_data:/backup/db-data:ro
          - /opt/supabase/.env:/backup/config/.env:ro

    ADDITIONALSERVICES

  # Zusätzliche Volumes hinzufügen
  - |
    cat >> /opt/supabase/docker-compose.yml << 'ADDITIONALVOLUMES'
      redis_data:
      portainer_data:
      uptime_kuma_data:
    ADDITIONALVOLUMES

  # Kong Service anpassen für ACME Plugin
  - sed -i 's/KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth/KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth,acme/' /opt/supabase/docker-compose.yml

  # Kong depends_on kongredis hinzufügen
  - sed -i '/container_name: supabase-kong/a\    depends_on:\n      - kongredis' /opt/supabase/docker-compose.yml

  # Storage Service für S3 konfigurieren
  - |
    sed -i 's/STORAGE_BACKEND: file/STORAGE_BACKEND: s3/' /opt/supabase/docker-compose.yml

  # DB Service Labels für Backup hinzufügen
  - |
    sed -i '/container_name: supabase-db/a\    labels:\n      - "docker-volume-backup.archive-pre=/bin/sh -c '"'"'pg_dumpall -U postgres > /var/lib/postgresql/data/backup_dump.sql'"'"'"\n      - "docker-volume-backup.archive-post=/bin/sh -c '"'"'rm -f /var/lib/postgresql/data/backup_dump.sql'"'"'"' /opt/supabase/docker-compose.yml

  # -------------------------------------------------------------------------
  # Firewall
  # -------------------------------------------------------------------------
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow 9443/tcp
  - ufw allow 3001/tcp
  - ufw --force enable

  # -------------------------------------------------------------------------
  # Fail2ban
  # -------------------------------------------------------------------------
  - systemctl enable fail2ban
  - systemctl start fail2ban

  # -------------------------------------------------------------------------
  # Supabase starten
  # -------------------------------------------------------------------------
  - cd /opt/supabase && docker compose pull
  - cd /opt/supabase && docker compose up -d

  # -------------------------------------------------------------------------
  # Optional: Restore von Backup
  # -------------------------------------------------------------------------
%{ if restore_from_backup }
  - sleep 60  # Warten bis alle Services gestartet sind
  - /opt/supabase/scripts/restore.sh "${backup_date}"
%{ endif }

  - echo "Supabase setup completed!"
