# =============================================================================
# Supabase Self-Hosting Environment Variables
# Generated by Terraform - Do not edit manually
# =============================================================================

# PostgreSQL
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=postgres

# JWT
JWT_SECRET=${jwt_secret}
JWT_EXPIRY=3600

# API Keys
ANON_KEY=${anon_key}
SERVICE_ROLE_KEY=${service_role_key}

# URLs
SITE_URL=https://${domain}
API_EXTERNAL_URL=https://${domain}
SUPABASE_PUBLIC_URL=https://${domain}

# Dashboard
DASHBOARD_USERNAME=${dashboard_username}
DASHBOARD_PASSWORD=${dashboard_password}

# Kong / SSL
KONG_HTTP_PORT=80
KONG_HTTPS_PORT=443
ACME_EMAIL=${acme_email}
ACME_DOMAIN=${domain}

# Secrets
SECRET_KEY_BASE=${secret_key_base}
VAULT_ENC_KEY=${vault_enc_key}

# Logflare
LOGFLARE_API_KEY=${logflare_api_key}

# S3 Storage
STORAGE_BACKEND=s3
S3_ENDPOINT=${s3_endpoint}
S3_REGION=${s3_region}
S3_ACCESS_KEY=${s3_access_key}
S3_SECRET_KEY=${s3_secret_key}
S3_STORAGE_BUCKET=${s3_storage_bucket}
S3_BACKUP_BUCKET=${s3_backup_bucket}

# Backup Notifications
NOTIFICATION_URLS=${notification_urls}

# Studio
STUDIO_DEFAULT_ORGANIZATION=Default Organization
STUDIO_DEFAULT_PROJECT=Default Project

# Features
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false
ENABLE_ANONYMOUS_USERS=false
DISABLE_SIGNUP=false

# SMTP (optional - configure if needed)
SMTP_ADMIN_EMAIL=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_SENDER_NAME=Supabase

# Mailer URLs
MAILER_URLPATHS_INVITE=/auth/v1/verify
MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
MAILER_URLPATHS_RECOVERY=/auth/v1/verify
MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify

# PostgREST
PGRST_DB_SCHEMAS=public,storage,graphql_public

# Functions
FUNCTIONS_VERIFY_JWT=false

# ImgProxy
IMGPROXY_ENABLE_WEBP_DETECTION=true

# Pooler
POOLER_TENANT_ID=supabase

# Docker Socket (for Vector)
DOCKER_SOCKET_LOCATION=/var/run/docker.sock
